name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrate how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
# core: 8.x
dependencies:
  - 'drupal:block'
  - 'webform:webform'
  - 'webform:webform_node'

# Information added by Drupal.org packaging script on 2019-03-28
version: '8.x-5.2'
core: '8.x'
project: 'webform'
datestamp: 1553768595
