label: 'Contenu modéré'
description: 'Trouver et modérer du contenu.'
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        title:
          label: Title
          separator: ', '
        type:
          label: 'Content type'
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        moderation_state:
          label: 'Moderation state'
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Content type'
        moderation_state:
          expose:
            label: 'Moderation state'
        langcode:
          expose:
            label: Langue
      title: 'Contenu modéré'
      empty:
        area_text_custom:
          content: "Aucun contenu modéré disponible. Seules les versions de contenu en attente, telles que 'Brouillon', sont listées ici."
  moderated_content:
    display_title: 'Contenu modéré'
