display:
  default:
    display_options:
      fields:
        reference_number:
          label: 'Numéro de demande'
        procurement_id:
          label: 'Numéro d''identification d''approvisionnement'
        vendor_name_1:
          label: 'Nom du fournisseur'
        contract_date:
          label: 'Date du contrat'
        economic_object_code:
          label: 'Code d’article économique'
        contract_period_start:
          label: 'Date de début du contrat'
        delivery_date:
          label: 'Date de clôture du contrat ou Date de livraison'
        contract_value_1:
          label: 'Valeur totale de contrat'
        amendment_value:
          label: 'Valeur originale de contrat'
        reporting_period:
          label: 'Période de déclaration'
        standing_offer_number:
          label: 'Commande subséquente à une l’offre à commandes ou arrangements en matière d’approvisionnement'
        commodity_code:
          label: 'Code de produit'
      title: 'Contrats gouvernementaux'
      footer:
        area_text_custom:
          content: '<p class="mrgn-tp-lg mrgn-bttm-xl"><a class="btn btn-primary" href="/fr/search/contrats">Retour à la recherche&nbsp;<span class="fa fa-undo"></span></a></p>'
