display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          reset_button_label: Réinitialiser
          exposed_sorts_label: Trier
      fields:
        title:
          label: 'Titre du jeu de données '
        body:
          label: Description
        field_suggested_dataset_dept:
          label: Organisation
        field_status:
          label: État
        field_vote_up_down:
          label: Votez
      title: 'Jeux de données suggérés par les utilisateurs'
