display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
          reset_button_label: Effacer
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '« première'
            last: 'dernière »'
      fields:
        nothing:
          alter:
            text: "{% set total_array = total|striptags|trim|number_format('2', '.', ',')|split('.') %}\r\n<div class=\"row\">\r\n  <div class=\"col-sm-9\">\r\n    {% if nothing_to_report_fr %}\r\n      <h2 class=\"h4 mrgn-tp-0\"><span class=\"hgl\">{{ nothing_to_report_fr }}</span></h2>\r\n      <p><small><strong>Organisation :</strong> {{ org_name_fr }}</small></p>\t\r\n    {% else %}\r\n      <h2 class=\"h4 mrgn-tp-0\"><a href=\"/fr/search/hospitalityq/reference/{{ id }}\"><span class=\"hgl\">{{ description_fr }}</span></a></h2>\r\n      <span class=\"hgl\">{{ name }}</span><br><small><span class=\"hgl\">{{ title_fr }}</span></small>\r\n      <p><small><strong>Organisation:</strong> <span class=\"hgl\">{{ org_name_fr }}</span><br>Ref # <span class=\"hgl\">{{ ref_number }}</span></small></p>\r\n    {%endif%}\r\n  </div>\r\n  <div class=\"col-sm-3 text-right\">\r\n    {% if nothing_to_report_fr %}\r\n      <small>{{ month_fr }}, {{ date_year }}</small>\r\n    {% else %}\r\n      <span class=\"h3 mrgn-tp-0\">{{ total_array[0] }}<sup><strong>,{{ total_array[1] }}</strong></sup> $</span><br />\r\n      <small>{{ start_date }}{% if (start_date != end_date) and (end_date is not empty) %} <br>au {{ end_date }}{% endif %}</small>\r\n    {% endif %}\r\n  </div>\r\n</div>"
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      header:
        result:
          content: '<p><strong>@total résultats trouvé(s)</strong></p>'
      empty:
        area_text_custom:
          content: "<p><strong>Aucun résultat trouvé.</strong></p> \r\n<p>Veuillez entrer un nouveau mot-clé.</p>\r\n<br/><br/>\r\n"
