display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        sid:
          label: 'Identifiant (ID) de la soumission'
          separator: ', '
        created:
          label: Créé
          separator: ', '
        remote_addr:
          label: 'Adresse IP distante'
          separator: ', '
        view_webform_submission:
          text: view
  embed_1:
    display_title: Intégré
  page_1:
    display_title: Page
