display:
  block_1:
    display_options:
      fields:
        nothing:
          alter:
            text: "<div class=\"row\">\r\n<div class=\"col-sm-8\">\r\n<h4 class=\"mrgn-tp-0 mrgn-bttm-sm\">{% if nothing_to_report_fr %}<span class=\"hgl\">{{ nothing_to_report_fr }}</span>{% else %}<a href=\"/fr/search/ati/reference/{{ id }}\">Req # <span class=\"hgl\">{{ request_number }}</span></a>{%endif%}</h4>\r\n<span class=\"hgl\">{{ request_summary_fr }}</span>\r\n<p><small><strong>Organisation:</strong> <span class=\"hgl\">{{ organization_fr}}</span></small></p>\r\n</div>\r\n<div class=\"col-sm-4 text-right\">\r\n{% if number_of_pages %}<span class=\"h3 mrgn-tp-0\">{{ number_of_pages }} <small>page(s)</small></span><br />{% endif %}\r\n<small>{{ month_name_fr }} {{ year }}</small>\r\n</div>\r\n</div>"
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
          reset_button_label: Effacer
      sorts:
        year:
          expose:
            label: Année
      filters:
        search_api_fulltext:
          expose:
            label: Recherche
      header:
        result:
          content: '<p><strong>Trouvé @total record(s) </strong></p>'
      pager:
        options:
          tags:
            previous: '‹ précédent'
            next: 'suivant ›'
            first: '‹‹ première'
            last: 'dernière ››'
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Recherche
          exposed_sorts_label: Trier
          reset_button_label: Effacer
      pager:
        options:
          tags:
            first: '‹ précédent'
            last: 'suivant ›'
      empty:
        area_text_custom:
          content: "<p><strong>Aucun résultat trouvé.</strong></p> \r\n<p>Veuillez entrer un nouveau mot-clé.</p>\r\n<br/><br/>\r\n"
  block_2:
    display_title: 'Demandes d’accès à l’information récentes'
    display_options:
      title: 'Demandes d’accès à l’information récentes'
      footer:
        area_text_custom:
          content: '<a href="/fr/search/ati">Voir tout</a>'
      fields:
        nothing:
          alter:
            text: '<a href="/fr/search/ati/reference/{{ id }}">{{ request_summary_fr }}</a>'
