label: Flux
display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
            first: "«\_premier"
            last: "dernier\_»"
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        feeds_feed_bulk_form:
          label: 'Mise à jour en masse'
          action_title: 'Pour la sélection'
        title:
          label: Titre
          separator: ', '
        type:
          label: Type
          separator: ', '
        name:
          label: Auteur
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        imported:
          label: Importé
          separator: ', '
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
        type:
          expose:
            label: Type
      title: Flux
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Flux
