default_list: ["Chnlovecomplaints","Russiangirldating","Russianwomendate","Trustedmedications","Thornhilljewellery",
               "Tuvanbenhtri","Hideuri","Girlgirlxvideo","Bacsilevanminh","Cort.as","Mewkid.net","Bitchute","Charmdate","Datereviews",
               "Oddsexch","Porn.cartoons","Ukrainianwomen","Remmont","Verbum","Hec.su","Femdomspanking"]
custom_list: ['']