default_list:
  - Chnlovecomplaints
  - Russiangirldating
  - Russianwomendate
  - Trustedmedications
  - Thornhilljewellery
  - Tuvanbenhtri
  - Hideuri
  - Girlgirlxvideo
  - Bacsilevanminh
  - Cort.as
  - Mewkid.net
  - Bitchute
  - Charmdate
  - Datereviews
  - Oddsexch
  - Porn.cartoons
  - Ukrainianwomen
  - Remmont
  - Verbum
  - Hec.su
  - Femdomspanking
custom_list:
  - Chnlovecomplaints
  - Russiangirldating
  - Russianwomendate
  - Trustedmedications
  - Thornhilljewellery
  - Tuvanbenhtri
  - Hideuri
  - Girlgirlxvideo
  - Bacsilevanminh
  - Cort.as
  - Mewkid.net
  - Bitchute
  - Charmdate
  - Datereviews
  - Oddsexch
  - Porn.cartoons
  - Ukrainianwomen
  - Remmont
  - Verbum
  - Hec.su
  - Femdomspanking
  - Amoxil
  - mewkid
  - Xandra
  - 'http://baclofen.us.com/]baclofen'
  - 'http://anafranil.us.com/]buy'
  - 'http://phenergan.us.com/]phenergan'
  - 'http://tadalafil247.com/]buy'
  - 'http://advair1.com/]advair'
  - 'http://suhagra2020.com/]suhagra'
  - 'http://indocinmed.com/]indocin'
  - 'http://acyclovirzov.com/]where'
  - 'http://antabusedsuf.com/]antabuse'
  - 'http://lasix.us.com/]generic'
  - 'http://sildalis365.us.com/]sildalis'
  - 'https://нериелтор.рф/krasnoyarsk-prodazha/prodam-treh-komnatnuyu-kvartiru/1-2-7%3E%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C'
  - 'https://hydra-shop.org/'
  - pussy
  - 'https://cutt.us/ass2020'
  - 'http://valtrexx.com/]valtrex'
  - finasteridealop.com
  - minoxidil
  - propecial
  - arimidex.us.org
  - glucophagge.com
  - glucophage
  - 'Купить сарай для дачи'
  - stroyderevo-91.ru
  - prazosin
  - cephalexin
  - cialis
  - 'Балaнс нaчислeн'
  - 'Выплатa пoлучена'
  - 'На ваш счет *3381 поступил перевод со счета *2653'
  - 'Платеж успешно завершен'
  - 'У вас отмена по операции ****BANK 7896'
  - bit.ly
  - hydra20original
  - datingsexygirls
  - sexy
  - sexygirls
  - datingsex
  - 'Вам перевод'
  - 'https://tinyurl.com/y5aohrne'
  - 'https://tinyurl.com/yycsxyth'
  - 'https://tinyurl.com/'
  - 'https://is.gd/'
  - viagra
  - 'google.com/url?q='
  - 'Chavvah EVE'
  - paulstephens1767@gmail.com
  - trading@benzinga.com
  - brownmelvyn911@gmail.com
  - Pinterest
  - Fuck
  - Shit
  - Stupid
  - Idiot
  - Moron
  - asshole
  - bastard
  - bitch
  - bollocks
  - brotherfucker
  - bugger
  - bullshit
  - child-fucker
  - 'Christ on a bike'
  - 'Christ on a cracker'
  - cocksucker
  - fatherfucker
  - frigger
  - fuck
  - goddamn
  - godsdamn
  - 'holy shit'
  - horseshit
  - 'Jesus Christ'
  - 'Jesus fuck'
  - 'Jesus H. Christ'
  - 'Jesus Harold Christ'
  - 'Jesus wept'
  - 'Jesus, Mary and Joseph'
  - 'Judas Priest'
  - motherfucker
  - nigga
  - prick
  - shit
  - 'shit ass'
  - shitass
  - sisterfucker
  - slut
  - 'son of a bitch'
  - 'son of a whore'
  - 'sweet Jesus'
  - twat
  - '>>>>>>>>'
  - danielfitzgerald10758@gmail.com
  - edwardnit@bestbuysteesss.ru
  - 'Chavvah Shoshan'
  - shoshan_7@hotmail.co.il
  - Chavvah
  - Slkfdf
  - erectile
  - 'erectile dysfunction'
  - portelli11@aol.com
  - sdiaz49@comcast.net
  - 'Premium Trader'
  - 'tyy tran I am'
  - tytytran19961226@gmail.com
  - enews@schaeffer.com
  - 'Supreme Court of Israel'
  - 'Holy Sunday'
  - 'Romantic Compatibility'
  - 'District Court of Jerusalem'
  - 'Holy Message'
  - 'Every Righteous People'
  - lixu99@shaw.ca
  - amitpatel3080@gmail.com
  - thaefiredey@gmail.com
  - 'Bernie Schaeffer'
  - 'Gianni Di Poce'
  - 'Louise Roy'
  - louise.roy2@icloud.com
  - Shemales
  - 'Shemales Blog'
  - 'Sex Movise'
  - jeannieoj69
  - gregna69@sora38.webmailm1.site
  - 'Honestly Help'
  - 'Holy Shabbat'
  - a7_miryam@hotmail.co.il
  - 'Netting you a $'
  - 'Chairman & CEO'
  - 'Schaeffer''s Investment Research'
  - service@sir-inc.com
  - 'http://www.schaeffersresearch.com'
  - 1-800-448-2080
  - 1-513-589-3800
  - 'UN Human Rights Council'
  - 'UN Human Rights Committee'
  - webadmin.hchr@unog.ch
  - lixu9@sprint.ca
  - Shoshan
  - 'Holy Monday'
  - 'Holy Tuesday'
  - 'Benzinga '
  - 'Benzinga Community'
  - 'Benzinga Small Cap Conference '
  - eventsemails@benzinga.com
  - 'Schaeffer''s Investment Research '
  - Benzinga.com
  - benzinga.com
  - 'Escort Israel'
  - lazarreenock@gmail.com
  - 'Visa visiter'
  - Lazarre
  - '4998504135'
  - sample@email.tst
  - Badoo
  - charmlive
  - 'dating app Badoo'
  - 'relationship software'
  - 'dating app'
  - fgdghhgh@pop.com
  - grantwilson7947@gmail.com
  - harringtonpeter67@gmail.com
  - amata-andrea@alice.it
  - 'Download TV Shows'
  - sofiyasamylkin
  - bndjcsfwhej
  - xrumer888@outlook.com
  - 1dexyrq@course-fitness.com
  - 2conv.ch@gmail.com
  - allaynewinnahn0927pmwc@gmail.com
  - sex
include_default_list: '1'
webform_list:
  - contact
