content_type_breadcrumb:
  type_app: 'main:menu_link_content:e9c65de2-964b-4d89-8051-7f59ff201351'
  type_article: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
  type_commitment: ''
  type_consultation: ''
  type_external: ''
  type_idea: 'main:menu_link_content:63a1b52e-2a34-45ee-a853-a53185c97947'
  type_landing_page: ''
  type_page: ''
  type_suggested_dataset: 'main:menu_link_content:cd47ab77-a418-46c6-8888-e2c83071358c'
  type_webform: ''
  view_pd_core_ati: null
  view_pd_core_ati_details: 'main:menu_link_content:703d982b-078a-4730-8fca-1aaeeefa1c83'
  view_pd_core_contracts_details: 'main:menu_link_content:866f23ae-722e-461d-bc29-b574003b3305'
  view_pd_core_grants_details: 'main:menu_link_content:028b0675-1dfc-401e-bd8c-82b1df82c861'
  view_pd_core_reclassification_details: 'main:menu_link_content:ec2b9da2-56d6-413c-9675-4693402201c1'
  view_pd_core_wrongdoing_details: 'main:menu_link_content:90ae4be4-48c7-4968-81cc-057a580a3c52'
  view_pd_core_travela_details: 'main:menu_link_content:616f6635-dbbe-4655-85f3-83e3bae19c43'
  view_pd_core_travelq_details: 'main:menu_link_content:145d17ff-c8f7-4475-9c09-d9f544b9b53b'
  view_pd_core_hospitalityq_details: 'main:menu_link_content:050da2b6-fce4-4f1b-9c2b-a943dd654ef1'
  view_pd_core_inventory_details: 'main:menu_link_content:4bbb4ef3-2311-4e99-bac7-e427ce380554'
  type_map: 'main:menu_link_content:d37cb41f-886f-4a94-a2d6-f51cf58d5514'
  vocabulary_app_categories: 'main:menu_link_content:e9c65de2-964b-4d89-8051-7f59ff201351'
  vocabulary_app_freetags: ''
  vocabulary_app_ribbon: ''
  vocabulary_blog_author: 'main:menu_link_content:a92b4794-19e1-465f-847c-5f1d9620ba37'
  vocabulary_commitment_freetags: ''
  vocabulary_consultation_status: ''
  vocabulary_departments: ''
  vocabulary_device_formats: ''
  vocabulary_idea_freetags: ''
  vocabulary_idea_status: ''
  vocabulary_site_structure: ''
  vocabulary_subscriptions: ''
