module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  alter_block: 0
  autologout: 0
  automated_cron: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_codemirror: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  content_type_breadcrumb: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  external_comment: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  memcache: 0
  menu_breadcrumb: 0
  menu_ui: 0
  mergenodes: 0
  metatag: 0
  metatag_dc: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  node: 0
  og_ext_user: 0
  og_ext_webform: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  user: 0
  views_ui: 0
  voting_webform: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  gcweb: 0
  stark: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
