schemas:
  bootstrap: 8000
  gcweb: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: 'https://open.canada.ca/sites/default/files/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
  node_user_picture: 0
logo:
  path: libraries/theme-gcweb/assets/sig-blk-en.svg
  url: ''
  use_default: 0
region_wells:
  branding: ''
  breadcrumb: ''
  language_toggle: ''
  banner: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  content: ''
  footer: ''
breadcrumb_home: 1
breadcrumb_title: 0
gcweb_footer: 1
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
