unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: details
time_limit: 10
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_app_form: false
  node_article_form: false
  node_commitment_form: false
  node_consultation_form: false
  node_external_form: false
  node_idea_form: false
  node_landing_page_form: false
  node_page_form: false
  node_suggested_dataset_form: false
  node_webform_form: false
  comment_comment_form: true
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
