determine_menu: true
disable_admin_page: true
append_current_page: false
current_page_as_link: false
append_member_page: false
member_page_as_link: false
remove_home: false
add_home: false
home_as_site_name: false
exclude_empty_url: false
menu_breadcrumb_menus:
  main:
    enabled: 1
    langhandle: 1
    weight: -10
    taxattach: 0
  admin:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  brand:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  footer:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  tools:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  account:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
_core:
  default_config_hash: MWtaH6iqiztF4V37kZZSpw-NZBbZijdlO_xMPIUCibY
