favicon:
  mimetype: image/vnd.microsoft.icon
  path: libraries/theme-gcweb/assets/favicon.ico
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: libraries/theme-gcweb/assets/sig-blk-en.svg
  url: ''
  use_default: true
_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
